// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1eB-HrEq6vrn5DTkzVot1fymHvnTmqt0',
    appId: '1:679555391180:web:a137657077282f4b0c6c69',
    messagingSenderId: '679555391180',
    projectId: 'myflutter-study-instagram',
    authDomain: 'myflutter-study-instagram.firebaseapp.com',
    storageBucket: 'myflutter-study-instagram.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF28VIn53fSDxBB2xbEybuxJBGcVKlRu4',
    appId: '1:679555391180:android:82a34478991da1350c6c69',
    messagingSenderId: '679555391180',
    projectId: 'myflutter-study-instagram',
    storageBucket: 'myflutter-study-instagram.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSrZ7lDKtmuKbPmQQtYUS7B9PmuJ8celM',
    appId: '1:679555391180:ios:73048124df5be1b60c6c69',
    messagingSenderId: '679555391180',
    projectId: 'myflutter-study-instagram',
    storageBucket: 'myflutter-study-instagram.appspot.com',
    iosClientId: '679555391180-9osmqcijp5fh8mc6lnj00ja1pcll603d.apps.googleusercontent.com',
    iosBundleId: 'com.example.myflutterStudyInstagram',
  );
}
